export const filmsData = [
  {
    id: 1,
    title: " 13 Reasons Why",
    engTitle: "United States",
    img: "https://m.media-amazon.com/images/M/MV5BYmRhZjkyMjEtNjRkMS00MDQ0LTg2NGMtMTQ3ZjE0NjJmMjM2L2ltYWdlXkEyXkFqcGdeQXVyNTY0MTkxMTg@._V1_.jpg",
    type: "Teenager, Mental",
    director: "Unknown",
    actors: "Unknown",
    year: "2018",
    nation: "United States",
    info: "Newcomer Katherine Langford plays the role of Hannah, a young woman who takes her own life. Two weeks after her tragic death, a classmate named Clay finds a mysterious box on his porch. Inside the box are recordings made by Hannah --- on whom Clay had a crush --- in which she explains the 13 reasons why she chose to commit suicide.",
    time: "100",
    rating: "5",
    numOfRating: "1000",
    quality: "4K",
    trailerUrl: "https://www.youtube.com/embed/poUq9ypynKs"
},
  {
    id: 2,
    title: "Avengers: Endgame",
    engTitle: "United States",
    img: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_FMjpg_UX1000_.jpg",
    type: "Fiction",
    director: "Unknown",
    actors: "Unknown",
    year: "2019",
    nation: "United States",
    info: "After Thanos, an intergalactic warlord, disintegrates half of the universe, the Avengers must reunite and assemble again to reinvigorate their trounced allies and restore balance.",
    time: "300",
    rating: "4.4",
    numOfRating: "300",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/TcMBFSGVi1c"
},
  {
    id: 3,
    title: "Breaking Bad",
    engTitle: "United States",
    img: "https://m.media-amazon.com/images/M/MV5BNDkyZThhNmMtZDBjYS00NDBmLTlkMjgtNWM2ZWYzZDQxZWU1XkEyXkFqcGdeQXVyMTMzNDExODE5._V1_FMjpg_UX1000_.jpg",
    type: "Storyteller",
    director: "Unknown",
    actors: "UKN",
    year: "2008",
    nation: "US",
    info: "Walter White, a chemistry teacher, discovers that he has cancer and decides to get into the meth-making business to repay his medical debts. His priorities begin to change when he partners with Jesse.",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/HhesaQXLuRY"
},
  {
    id: 4,
    title: "Bridgerton",
    engTitle: "United Kingdom",
    img: "https://m.media-amazon.com/images/M/MV5BNjk4MDdhODctMmFhYi00ZTNhLThlN2UtN2NhZGY0OGFlMWEwXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg",
    type: "Old-story",
    director: "UKN",
    actors: "UKN",
    year: "2017",
    nation: "UK",
    info: "During the Regency era in England, eight close-knit siblings of the powerful Bridgerton family attempt to find love.",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/gpv7ayf_tyE"
},
  {
    id: 5,
    title: "Alice In Borderland",
    engTitle: "Japan",
    img: "https://m.media-amazon.com/images/M/MV5BZmUwMGI4M2QtYmRlYy00NDQ1LThjNDAtYTI4NDNiNDg5MDViXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg",
    type: "Action",
    director: "UKN",
    actors: "UKN",
    year: "2020",
    nation: "JPN",
    info: "Obsessed gamer Arisu suddenly finds himself in a strange, emptied-out version of Tokyo in which he and his friends must compete in dangerous games in order to survive.",
    time: "180",
    rating: "4.8",
    numOfRating: "255",
    quality: "Full HD",
    trailerUrl: "https://www.youtube.com/embed/vba9e_hSvro"
},
//   {
//     id: 6,
//     title: "Mẹ Chồng",
//     engTitle: "Mother in law",
//     img: "assets/images/mechong.jpg",
//     type: "Chính kịch",
//     director: "Lê Hoàng",
//     actors: "Thanh Hằng, Diễm My, Lan Khuê, Ngọc Quyên,...",
//     year: "2017",
//     nation: "Việt Nam",
//     info: "Mẹ chồng là một câu chuyện xảy ra ở bối cảnh giả định mang tên Đại Điền vào những năm 1945 - 1950, xoay quanh cuộc đời cô Ba Trân (Thanh Hằng), một người phụ nữ Nam Bộ chịu nhiều ảnh hưởng của nền giáo dục Nho giáo. Từ khi về làm dâu, Ba Trân luôn phải chịu nhiều bất hạnh với những quy củ hà khắc từ gia đình nhà chồng. Ngỡ tưởng, những bi thương từng nếm trải sẽ khiến Ba Trân trở nên vị tha và nhân hậu hơn với con dâu mình. Thế nhưng, do sức ép của việc gìn giữ và duy trì nền nếp dòng họ, cô lại tiếp tục lặp lại con đường nhân bản bi kịch của mình lên những người phụ nữ khác khi cô trở thành mẹ chồng.",
//     time: "180",
//     rating: "4.8",
//     numOfRating: "255",
//     quality: "Full HD",
//     trailerUrl: "https://www.youtube.com/embed/LBrBwtACGeU"
// },
//   {
//     id: 7,
//     title: "Nắng",
//     engTitle: "Sunny",
//     img: "assets/images/nang.jpg",
//     type: "Tình cảm, tâm lý",
//     director: "Đồng Đăng Giao",
//     actors: "Kim Thư, Thu Trang, Trấn Thành, Kiều Minh Tuấn,...",
//     year: "2016",
//     nation: "Việt Nam",
//     info: "Bộ phim Nắng khắc họa tình mẫu tử thiêng liêng của người mẹ thiểu năng tên Mưa với đứa con gái bé bỏng tên Nắng. Hai mẹ con Mưa, Nắng là những người ở đáy cùng của xã hội. Họ vất vả mưu sinh bằng nghề bán vé số, lượm ve chai. Trong khi người mẹ khù khờ, ngờ nghệch, cô gái nhỏ của chị lại lanh lợi, thông minh. Những tình cảm yêu thương, quấn quýt của hai mẹ con dành cho nhau lồng trong bối cảnh cuộc sống đời thường mang đến góc nhìn dễ thương, dung dị.",
//     time: "180",
//     rating: "4.8",
//     numOfRating: "255",
//     quality: "Full HD",
//     trailerUrl: "https://www.youtube.com/embed/tyaq_lOwqmg"
// },
//   {
//     id: 8,
//     title: "Tháng Năm Rực Rỡ",
//     engTitle: "Brilliant May",
//     img: "assets/images/thangnamrucro.jpg",
//     type: "Hài hước, tâm lý",
//     director: "Nguyễn Quang Dũng",
//     actors: "Anh Thư, Mỹ Duyên, Hồng Ánh, Thanh Hằng,...",
//     year: "2018",
//     nation: "Việt Nam",
//     info: "THÁNG NĂM RỰC RỠ là câu chuyện về tình bạn, về thời tuổi trẻ cuồng nhiệt của một nhóm bạn gái thời trung học. Bộ phim là hành trình đi tìm lại những ký ức thanh xuân của Hiểu Phương (Hồng Ánh) và nhóm nữ quái Ngựa Hoang. Tình cờ gặp lại người bạn cũ Mỹ Dung (Thanh Hằng) và cũng là trưởng nhóm Ngựa Hoang, Hiểu Phương đau xót khi biết bạn đang mắc bệnh hiểm nghèo. Để thực hiện tâm nguyện của bạn thân, Hiểu Phương quyết tâm tìm lại các thành viên của nhóm Ngựa Hoang. Hành trình đi tìm những người bạn cũ cũng chính là hành trình để Hiểu Phương trở về với những “THÁNG NĂM RỰC RỠ” của cuộc đời mình.",
//     time: "180",
//     rating: "4.8",
//     numOfRating: "255",
//     quality: "Full HD",
//     trailerUrl: "https://www.youtube.com/embed/RyQeBPpZqdY"  
// },
//   {
//     id: 9,
//     title: "Tèo em",
//     engTitle: "Teo Em",
//     img: "assets/images/teoem.jpg",
//     type: "Hài hước",
//     director: "Charlie Nguyễn",
//     actors: "Thái Hòa, Johny Nguyễn, Lan Ngọc,...",
//     year: "2015",
//     nation: "Việt Nam",
//     info: "Johnny Trí Nguyễn và Thái Hòa vào vai hai anh em Tí, Tèo có cuộc sống và tính cách khác nhau. Một người lanh lợi, lịch lãm; kẻ còn lại thì cù lần, ngây ngô. Họ buộc phải đi cùng nhau trên một chuyến xe về thị xã Sa Đéc, chạy đua với thời gian nhằm cứu vãn một mối tình. Trên đường đi, sự khác biệt làm nảy sinh xung đột và dẫn tới những câu chuyện dở khóc dở cười.",
//     time: "180",
//     rating: "4.8",
//     numOfRating: "255",
//     quality: "Full HD",
//     trailerUrl: "https://www.youtube.com/embed/oRvzM1eX5ow" 
// },
];
